//! Generates owner contract rules from `contracts/*/spec.json`.
//!
//! Generated Rust and JSON Schema files go to `OUT_DIR`. Portable projections
//! committed under `contracts/` are checked against those generated bytes by
//! owner tests, so editable rule data remains in the specs while downstream
//! consumers have stable exact-pin paths.

use serde_json::Value;
use std::collections::HashSet;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    generate_zone_id(&out_dir);
    generate_zone_path(&out_dir);
}

fn contract_path(relative: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join(relative)
        .canonicalize()
        .unwrap_or_else(|_| panic!("{relative} must exist"))
}

fn read_json(path: &Path, label: &str) -> Value {
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|error| panic!("{label} is unreadable: {error}"));
    serde_json::from_str(&raw).unwrap_or_else(|error| panic!("{label} is not valid JSON: {error}"))
}

fn text<'a>(value: &'a Value, pointer: &str, label: &str) -> &'a str {
    value
        .pointer(pointer)
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("{label} must contain string {pointer}"))
}

fn boolean(value: &Value, pointer: &str, label: &str) -> bool {
    value
        .pointer(pointer)
        .and_then(Value::as_bool)
        .unwrap_or_else(|| panic!("{label} must contain boolean {pointer}"))
}

fn strings(value: &Value, pointer: &str, label: &str) -> Vec<String> {
    value
        .pointer(pointer)
        .and_then(Value::as_array)
        .unwrap_or_else(|| panic!("{label} must contain array {pointer}"))
        .iter()
        .map(|item| {
            item.as_str()
                .unwrap_or_else(|| panic!("{label} {pointer} entries must be strings"))
                .to_string()
        })
        .collect()
}

fn single_char(value: &str, label: &str) -> char {
    value
        .parse::<char>()
        .unwrap_or_else(|_| panic!("{label} must contain exactly one Unicode scalar"))
}

fn require_text(value: &Value, pointer: &str, expected: &str, label: &str) {
    let actual = text(value, pointer, label);
    assert_eq!(
        actual, expected,
        "{label} {pointer}={actual:?} is unsupported; expected {expected:?}"
    );
}

fn generate_zone_id(out_dir: &Path) {
    let spec_path = contract_path("contracts/zone-id/spec.json");
    println!("cargo:rerun-if-changed={}", spec_path.display());

    let spec = read_json(&spec_path, "contracts/zone-id/spec.json");
    let contract_id = text(&spec, "/$id", "zone-id spec");
    require_text(
        &spec,
        "/projection/json_schema",
        "schema.json",
        "zone-id spec",
    );
    require_text(
        &spec,
        "/projection/fixtures",
        "vectors.json",
        "zone-id spec",
    );
    require_text(&spec, "/projection/scope", "lexical", "zone-id spec");
    require_text(
        &spec,
        "/projection/reserved_values",
        "owner-runtime-constants",
        "zone-id spec",
    );
    let min = spec["length"]["min"].as_u64().expect("length.min");
    let max = spec["length"]["max"].as_u64().expect("length.max");
    assert!(min > 0 && max >= min, "zone-id length bounds are invalid");
    let charset = spec["charset"]["allowed"]
        .as_str()
        .expect("charset.allowed");
    let no_leading = spec["edges"]["no_leading"]
        .as_str()
        .expect("edges.no_leading");
    let no_trailing = spec["edges"]["no_trailing"]
        .as_str()
        .expect("edges.no_trailing");
    let no_leading_char = single_char(no_leading, "zone-id edges.no_leading");
    let no_trailing_char = single_char(no_trailing, "zone-id edges.no_trailing");

    let reserved: Vec<String> = spec["reserved"]["constants"]
        .as_array()
        .expect("reserved.constants")
        .iter()
        .map(|v| v.as_str().expect("reserved constant name").to_string())
        .collect();

    let reserved_refs = reserved
        .iter()
        .map(|name| format!("        crate::constants::{name},"))
        .collect::<Vec<_>>()
        .join("\n");

    let generated = format!(
        "// @generated from contracts/zone-id/spec.json — do not edit.\n\
         // Regenerated on every build; this file lives in OUT_DIR, not the tree.\n\
         \n\
         /// Stable owner identifier for this contract revision family.\n\
         pub const ZONE_ID_CONTRACT_ID: &str = {contract_id:?};\n\
         /// Shortest permitted zone id.\n\
         pub const ZONE_ID_MIN_LEN: usize = {min};\n\
         /// Longest permitted zone id.\n\
         pub const ZONE_ID_MAX_LEN: usize = {max};\n\
         /// Every character a zone id may contain.\n\
         pub const ZONE_ID_CHARSET: &str = {charset:?};\n\
         /// Character a zone id may not start with.\n\
         pub const ZONE_ID_NO_LEADING: char = {no_leading:?};\n\
         /// Character a zone id may not end with.\n\
         pub const ZONE_ID_NO_TRAILING: char = {no_trailing:?};\n\
         /// Ids the kernel owns; tenants may not create them.\n\
         pub const ZONE_ID_RESERVED: &[&str] = &[\n{reserved_refs}\n    ];\n\
         /// JSON Schema projection of the portable lexical form.\n\
         pub const ZONE_ID_SCHEMA_JSON: &str = include_str!(concat!(env!(\"OUT_DIR\"), \"/zone_id_schema.json\"));\n",
        no_leading = no_leading_char,
        no_trailing = no_trailing_char,
    );

    let bad_char = if charset.contains('_') { '!' } else { '_' };
    let zone_id_fixtures = vec![
        ("shortest", "boundary", "a".repeat(min as usize), true),
        ("longest", "boundary", "a".repeat(max as usize), true),
        ("canonical", "positive", "cloud-user-1001".to_string(), true),
        (
            "uuid",
            "positive",
            "550e8400-e29b-41d4-a716-446655440000".to_string(),
            true,
        ),
        (
            "too-short",
            "boundary",
            "a".repeat((min - 1) as usize),
            false,
        ),
        (
            "too-long",
            "boundary",
            "a".repeat((max + 1) as usize),
            false,
        ),
        ("leading", "negative", format!("{no_leading}leading"), false),
        (
            "trailing",
            "negative",
            format!("trailing{no_trailing}"),
            false,
        ),
        ("uppercase", "negative", "Has-Upper".to_string(), false),
        (
            "bad-character",
            "negative",
            format!("has{bad_char}char"),
            false,
        ),
        (
            "prefixed-uuid",
            "negative",
            "org:550e8400-e29b-41d4-a716-446655440000".to_string(),
            false,
        ),
        ("terminal-newline", "negative", "abc\n".to_string(), false),
    ];
    let vector_lines = zone_id_fixtures
        .iter()
        .map(|(_, _, id, should_accept)| format!("    ({id:?}, {should_accept}),"))
        .collect::<Vec<_>>()
        .join("\n");
    let vectors = format!(
        "/// Cases derived from the spec: `(id, should_be_accepted)`.\n\
         pub const ZONE_ID_VECTORS: &[(&str, bool)] = &[\n{vector_lines}\n];\n\
         /// Portable JSON form of the generated lexical vectors.\n\
         pub const ZONE_ID_VECTORS_JSON: &str = include_str!(concat!(env!(\"OUT_DIR\"), \"/zone_id_vectors.json\"));\n"
    );

    std::fs::write(
        out_dir.join("zone_id_rules.rs"),
        format!("{generated}\n{vectors}"),
    )
    .expect("failed to write generated zone-id rules");

    let fixture_cases = zone_id_fixtures
        .iter()
        .map(|(id, class, value, should_accept)| {
            serde_json::json!({
                "id": id,
                "class": class,
                "value": value,
                "expected": if *should_accept { "accept" } else { "reject" }
            })
        })
        .collect::<Vec<_>>();
    let fixture_document = serde_json::json!({
        "provenance": {
            "owner": "nexus-vfs",
            "canonical_source": "contracts/zone-id/spec.json",
            "contract_id": contract_id,
            "generation": "derived"
        },
        "cases": fixture_cases
    });
    let fixture_json = format!(
        "{}\n",
        serde_json::to_string_pretty(&fixture_document).expect("serialize zone-id vectors")
    );
    std::fs::write(out_dir.join("zone_id_vectors.json"), fixture_json)
        .expect("failed to write generated zone-id vectors");

    let allowed = charset.chars().map(regex_class_escape).collect::<String>();
    let leading_allowed = charset
        .chars()
        .filter(|ch| *ch != no_leading_char)
        .map(regex_class_escape)
        .collect::<String>();
    let trailing_allowed = charset
        .chars()
        .filter(|ch| *ch != no_trailing_char)
        .map(regex_class_escape)
        .collect::<String>();
    assert!(
        !leading_allowed.is_empty() && !trailing_allowed.is_empty(),
        "zone-id charset has no edge-safe characters"
    );
    let disallowed_pattern = format!("[^{allowed}]");
    let leading_pattern = format!("^[{leading_allowed}]");
    let trailing_pattern = format!("[{trailing_allowed}]$");
    let schema = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": contract_id,
        "title": "ZoneId",
        "description": "Portable lexical ZoneId form. Tenant creation additionally rejects owner-reserved constants at runtime.",
        "type": "string",
        "minLength": min,
        "maxLength": max,
        "allOf": [
            { "not": { "pattern": disallowed_pattern } },
            { "pattern": leading_pattern },
            { "pattern": trailing_pattern }
        ],
        "x-sudo-owner": {
            "repository": "nexus-vfs",
            "canonical_source": "contracts/zone-id/spec.json",
            "fixture_source": "contracts/zone-id/vectors.json",
            "generated": true
        },
        "x-sudo-semantics": {
            "projection_scope": "lexical",
            "case_folding": "none",
            "reserved_constants": reserved,
            "reserved_values_in_lexical_projection": false,
            "tenant_create_validator": "contracts::zone_id::validate_zone_id"
        }
    });
    let schema_json = format!(
        "{}\n",
        serde_json::to_string_pretty(&schema).expect("serialize zone-id schema")
    );
    std::fs::write(out_dir.join("zone_id_schema.json"), schema_json)
        .expect("failed to write generated zone-id schema");
}

fn regex_class_escape(ch: char) -> String {
    match ch {
        '\0' => ch.to_string(),
        '\\' => r"\\".to_string(),
        ']' => r"\]".to_string(),
        '^' => r"\^".to_string(),
        '-' => r"\-".to_string(),
        other => other.to_string(),
    }
}

fn generate_zone_path(out_dir: &Path) {
    let spec_path = contract_path("contracts/zone-path/spec.json");
    let cases_path = contract_path("contracts/zone-path/cases.json");
    println!("cargo:rerun-if-changed={}", spec_path.display());
    println!("cargo:rerun-if-changed={}", cases_path.display());

    let spec = read_json(&spec_path, "contracts/zone-path/spec.json");
    let cases = read_json(&cases_path, "contracts/zone-path/cases.json");
    let contract_id = text(&spec, "/$id", "zone-path spec");
    let owner = text(&spec, "/owner", "zone-path spec");
    assert_eq!(owner, "nexus-vfs", "unsupported zone-path owner");
    let scope = text(&spec, "/representation/scope", "zone-path spec");
    assert_eq!(scope, "zone-relative", "unsupported ZonePath scope");
    assert!(
        boolean(&spec, "/representation/absolute", "zone-path spec"),
        "ZonePath must remain absolute"
    );
    require_text(&spec, "/representation/empty", "reject", "zone-path spec");
    require_text(
        &spec,
        "/representation/repeated_separators",
        "reject",
        "zone-path spec",
    );
    require_text(
        &spec,
        "/representation/trailing_separator",
        "root-only",
        "zone-path spec",
    );
    let input_encoding = text(&spec, "/encoding/input", "zone-path spec");
    assert_eq!(input_encoding, "UTF-8", "unsupported ZonePath encoding");
    let unicode_scalar_values_only = boolean(
        &spec,
        "/encoding/unicode_scalar_values_only",
        "zone-path spec",
    );
    assert!(
        unicode_scalar_values_only,
        "ZonePath JSON strings must contain only Unicode scalar values"
    );
    let unicode_normalization = text(&spec, "/encoding/unicode_normalization", "zone-path spec");
    assert_eq!(
        unicode_normalization, "none",
        "unsupported Unicode normalization"
    );
    let case_folding = text(&spec, "/encoding/case_folding", "zone-path spec");
    assert_eq!(case_folding, "none", "unsupported ZonePath case folding");
    let percent_decoding = text(&spec, "/encoding/percent_decoding", "zone-path spec");
    assert_eq!(
        percent_decoding, "none",
        "unsupported ZonePath percent decoding"
    );
    let automatic_normalization = boolean(&spec, "/normalization/automatic", "zone-path spec");
    assert!(
        !automatic_normalization,
        "ZonePath must not normalize automatically"
    );
    let validation_timing = text(&spec, "/normalization/validation_timing", "zone-path spec");
    assert_eq!(
        validation_timing, "before-authorization-routing-storage",
        "unsupported ZonePath validation timing"
    );
    let legacy_raw_vfs_paths_in_scope = boolean(
        &spec,
        "/compatibility/legacy_raw_vfs_paths_in_scope",
        "zone-path spec",
    );
    assert!(
        !legacy_raw_vfs_paths_in_scope,
        "legacy raw VFS paths must remain outside the strict ZonePath contract"
    );
    let persisted_keys_rewritten = boolean(
        &spec,
        "/compatibility/persisted_keys_rewritten",
        "zone-path spec",
    );
    assert!(
        !persisted_keys_rewritten,
        "the ZonePath contract must not rewrite persisted keys"
    );
    require_text(
        &spec,
        "/projection/json_schema",
        "schema.json",
        "zone-path spec",
    );
    require_text(
        &spec,
        "/projection/json_meta_schema",
        "meta-schema.json",
        "zone-path spec",
    );
    let meta_schema_id = text(&spec, "/projection/meta_schema_id", "zone-path spec");
    let required_vocabulary = text(&spec, "/projection/required_vocabulary", "zone-path spec");
    let zone_path_keyword = text(&spec, "/projection/zone_path_keyword", "zone-path spec");
    require_text(
        &spec,
        "/projection/fixtures",
        "cases.json",
        "zone-path spec",
    );

    let root = text(&spec, "/representation/root", "zone-path spec");
    let separator_text = text(&spec, "/representation/separator", "zone-path spec");
    let separator = single_char(separator_text, "zone-path separator");
    assert_eq!(
        root, separator_text,
        "ZonePath root must equal its separator"
    );

    let forbidden_segments = strings(&spec, "/segments/forbidden_exact", "zone-path spec");
    assert!(
        !forbidden_segments.is_empty(),
        "zone-path forbidden_exact must not be empty"
    );
    assert_eq!(
        forbidden_segments.as_slice(),
        [".", ".."],
        "the portable schema generator currently supports exact dot segments"
    );
    let forbidden_character_strings =
        strings(&spec, "/segments/forbidden_characters", "zone-path spec");
    let forbidden_characters: Vec<char> = forbidden_character_strings
        .iter()
        .map(|item| single_char(item, "zone-path forbidden character"))
        .collect();
    assert!(
        forbidden_characters.contains(&'\0') && forbidden_characters.contains(&'\\'),
        "zone-path forbidden characters must include NUL and backslash"
    );

    assert_eq!(
        text(&cases, "/provenance/owner", "zone-path cases"),
        "nexus-vfs"
    );
    assert_eq!(
        text(&cases, "/provenance/canonical_source", "zone-path cases"),
        "contracts/zone-path/spec.json"
    );
    assert_eq!(
        text(&cases, "/provenance/contract_id", "zone-path cases"),
        contract_id
    );

    let case_values = cases["cases"]
        .as_array()
        .expect("zone-path cases must contain cases array");
    assert!(!case_values.is_empty(), "zone-path cases must not be empty");
    let mut ids = HashSet::new();
    let mut has_positive = false;
    let mut has_negative = false;
    let mut has_boundary = false;
    let mut vector_lines = Vec::with_capacity(case_values.len());
    for case in case_values {
        let id = case["id"].as_str().expect("zone-path case id");
        assert!(ids.insert(id), "duplicate zone-path case id {id:?}");
        let class = case["class"].as_str().expect("zone-path case class");
        let path = case["path"].as_str().expect("zone-path case path");
        let expected = case["expected"].as_str().expect("zone-path case expected");
        let should_accept = match expected {
            "accept" => true,
            "reject" => false,
            other => panic!("zone-path case {id:?} has unsupported expected={other:?}"),
        };
        match class {
            "positive" => {
                assert!(should_accept, "positive case {id:?} must accept");
                has_positive = true;
            }
            "negative" => {
                assert!(!should_accept, "negative case {id:?} must reject");
                has_negative = true;
            }
            "boundary" => has_boundary = true,
            other => panic!("zone-path case {id:?} has unsupported class={other:?}"),
        }
        vector_lines.push(format!(
            "    ZonePathVector {{ id: {id:?}, class: {class:?}, path: {path:?}, should_accept: {should_accept} }},"
        ));
    }
    assert!(has_positive, "zone-path cases contain no positive class");
    assert!(has_negative, "zone-path cases contain no negative class");
    assert!(has_boundary, "zone-path cases contain no boundary class");

    let forbidden_segments_rust = format!("&{:?}", forbidden_segments);
    let forbidden_characters_rust = format!("&{:?}", forbidden_characters);
    let vectors = vector_lines.join("\n");
    let generated = format!(
        "// @generated from contracts/zone-path/spec.json and cases.json — do not edit.\n\
         // Regenerated on every build; this file lives in OUT_DIR, not the tree.\n\
         \n\
         /// Stable owner identifier used by exact-pinned projections.\n\
         pub const ZONE_PATH_CONTRACT_ID: &str = {contract_id:?};\n\
         /// Required JSON Schema dialect for the portable projection.\n\
         pub const ZONE_PATH_META_SCHEMA_ID: &str = {meta_schema_id:?};\n\
         /// Required JSON Schema vocabulary that enforces ZonePath semantics.\n\
         pub const ZONE_PATH_REQUIRED_VOCABULARY: &str = {required_vocabulary:?};\n\
         /// The only spelling of the zone-relative root.\n\
         pub const ZONE_PATH_ROOT: &str = {root:?};\n\
         /// The platform-independent path separator.\n\
         pub const ZONE_PATH_SEPARATOR: char = {separator:?};\n\
         /// Segments refused exactly, without decoding or normalization.\n\
         pub const ZONE_PATH_FORBIDDEN_SEGMENTS: &[&str] = {forbidden_segments_rust};\n\
         /// Characters that cannot occur in a ZonePath.\n\
         pub const ZONE_PATH_FORBIDDEN_CHARACTERS: &[char] = {forbidden_characters_rust};\n\
         /// Owner cases derived from the portable fixture file.\n\
         pub const ZONE_PATH_VECTORS: &[ZonePathVector] = &[\n{vectors}\n];\n\
         /// JSON Schema projection generated from the owner source.\n\
         pub const ZONE_PATH_SCHEMA_JSON: &str = include_str!(concat!(env!(\"OUT_DIR\"), \"/zone_path_schema.json\"));\n\
         /// Required meta-schema generated from the owner source.\n\
         pub const ZONE_PATH_META_SCHEMA_JSON: &str = include_str!(concat!(env!(\"OUT_DIR\"), \"/zone_path_meta_schema.json\"));\n"
    );
    std::fs::write(out_dir.join("zone_path_rules.rs"), generated)
        .expect("failed to write generated zone-path rules");

    let zone_path_rule = serde_json::json!({
        "scope": scope,
        "absolute": true,
        "root": root,
        "separator": separator_text,
        "empty": "reject",
        "repeated_separators": "reject",
        "trailing_separator": "root-only",
        "forbidden_exact_segments": forbidden_segments,
        "forbidden_characters": forbidden_character_strings,
        "unicode_scalar_values_only": unicode_scalar_values_only,
        "unicode_normalization": unicode_normalization,
        "case_folding": case_folding,
        "percent_decoding": percent_decoding,
        "automatic_normalization": automatic_normalization
    });

    let mut schema = serde_json::json!({
        "$schema": meta_schema_id,
        "$id": contract_id,
        "title": "ZonePath",
        "description": "Strict zone-relative absolute path for new product-independent reference boundaries.",
        "type": "string",
        "minLength": 1,
        "x-sudo-owner": {
            "repository": owner,
            "canonical_source": "contracts/zone-path/spec.json",
            "fixture_source": "contracts/zone-path/cases.json",
            "generated": true
        },
        "x-sudo-semantics": {
            "scope": scope,
            "root": root,
            "separator": separator_text,
            "input_encoding": input_encoding,
            "unicode_scalar_values_only": unicode_scalar_values_only,
            "unicode_normalization": unicode_normalization,
            "case_folding": case_folding,
            "percent_decoding": percent_decoding,
            "automatic_normalization": automatic_normalization,
            "validation_timing": validation_timing,
            "legacy_raw_vfs_paths_in_scope": legacy_raw_vfs_paths_in_scope,
            "persisted_keys_rewritten": persisted_keys_rewritten
        }
    });
    schema
        .as_object_mut()
        .expect("zone-path schema must be an object")
        .insert(zone_path_keyword.to_string(), zone_path_rule);
    let schema_json = format!(
        "{}\n",
        serde_json::to_string_pretty(&schema).expect("serialize zone-path schema")
    );
    std::fs::write(out_dir.join("zone_path_schema.json"), schema_json)
        .expect("failed to write generated zone-path schema");

    let draft_meta_schema = "https://json-schema.org/draft/2020-12/schema";
    let mut vocabularies = serde_json::Map::new();
    for vocabulary in [
        "https://json-schema.org/draft/2020-12/vocab/core",
        "https://json-schema.org/draft/2020-12/vocab/applicator",
        "https://json-schema.org/draft/2020-12/vocab/unevaluated",
        "https://json-schema.org/draft/2020-12/vocab/validation",
        "https://json-schema.org/draft/2020-12/vocab/meta-data",
        "https://json-schema.org/draft/2020-12/vocab/format-annotation",
        "https://json-schema.org/draft/2020-12/vocab/content",
    ] {
        vocabularies.insert(vocabulary.to_string(), Value::Bool(true));
    }
    vocabularies.insert(required_vocabulary.to_string(), Value::Bool(true));

    let mut keyword_properties = serde_json::Map::new();
    keyword_properties.insert(
        zone_path_keyword.to_string(),
        serde_json::json!({
            "type": "object",
            "additionalProperties": false,
            "required": [
                "scope",
                "absolute",
                "root",
                "separator",
                "empty",
                "repeated_separators",
                "trailing_separator",
                "forbidden_exact_segments",
                "forbidden_characters",
                "unicode_scalar_values_only",
                "unicode_normalization",
                "case_folding",
                "percent_decoding",
                "automatic_normalization"
            ],
            "properties": {
                "scope": { "const": "zone-relative" },
                "absolute": { "const": true },
                "root": { "type": "string", "minLength": 1 },
                "separator": { "type": "string", "minLength": 1, "maxLength": 1 },
                "empty": { "const": "reject" },
                "repeated_separators": { "const": "reject" },
                "trailing_separator": { "const": "root-only" },
                "forbidden_exact_segments": {
                    "type": "array",
                    "minItems": 1,
                    "items": { "type": "string" }
                },
                "forbidden_characters": {
                    "type": "array",
                    "minItems": 1,
                    "items": { "type": "string", "minLength": 1, "maxLength": 1 }
                },
                "unicode_scalar_values_only": { "const": true },
                "unicode_normalization": { "const": "none" },
                "case_folding": { "const": "none" },
                "percent_decoding": { "const": "none" },
                "automatic_normalization": { "const": false }
            }
        }),
    );
    let meta_schema = serde_json::json!({
        "$schema": draft_meta_schema,
        "$id": meta_schema_id,
        "$vocabulary": vocabularies,
        "$dynamicAnchor": "meta",
        "title": "nexus-vfs ZonePath contract dialect",
        "allOf": [
            { "$ref": draft_meta_schema }
        ],
        "properties": keyword_properties
    });
    let meta_schema_json = format!(
        "{}\n",
        serde_json::to_string_pretty(&meta_schema).expect("serialize zone-path meta-schema")
    );
    std::fs::write(out_dir.join("zone_path_meta_schema.json"), meta_schema_json)
        .expect("failed to write generated zone-path meta-schema");
}
