#!/usr/bin/env node
// Copies the service definitions from this repository's proto tree into the
// package so they can ship to npm. The copies are generated, never committed
// (see .gitignore) — that is what makes drift structurally impossible:
// there is exactly one editable copy of each proto in this repo, and every
// Node consumer loads a byte-identical copy of it.
//
// `--check` verifies existing copies are current instead of writing, for CI.
//
// The raft protos come as a closure, not a single file: transport.proto
// imports commands.proto, which imports core/metadata.proto. protobufjs
// resolves an import against what is already in the root, so the client parses
// all three into one root — leaf first. Shipping only the file that declares
// the service would leave `RaftCommand` and friends unresolvable.

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const repoRoot = dirname(dirname(packageRoot))

/**
 * Each entry ships as a byte-identical copy plus a named export. Order is the
 * order the client parses them in, so a file appears after everything it
 * imports.
 */
const PROTOS = [
  { export: 'VFS_PROTO', parts: ['proto', 'nexus', 'grpc', 'vfs', 'vfs.proto'] },
  { export: 'CORE_METADATA_PROTO', parts: ['proto', 'nexus', 'core', 'metadata.proto'] },
  { export: 'RAFT_COMMANDS_PROTO', parts: ['proto', 'nexus', 'raft', 'commands.proto'] },
  { export: 'RAFT_TRANSPORT_PROTO', parts: ['proto', 'nexus', 'raft', 'transport.proto'] },
].map(entry => {
  const relative = join(...entry.parts)
  return {
    exportName: entry.export,
    relative,
    posix: entry.parts.join('/'),
    source: join(repoRoot, relative),
    destination: join(packageRoot, relative),
  }
})

const generated = join(packageRoot, 'src', 'generated', 'proto.ts')

for (const proto of PROTOS) {
  if (!existsSync(proto.source)) {
    console.error(`sync-proto: source proto not found at ${proto.source}`)
    process.exit(1)
  }
  proto.contents = readFileSync(proto.source)
}

if (process.argv.includes('--check')) {
  if (!existsSync(generated)) {
    console.error('sync-proto: src/generated/proto.ts is missing — run `npm run sync-proto`')
    process.exit(1)
  }
  for (const proto of PROTOS) {
    if (!existsSync(proto.destination) || !readFileSync(proto.destination).equals(proto.contents)) {
      console.error(`sync-proto: ${proto.relative} is stale — run \`npm run sync-proto\``)
      process.exit(1)
    }
  }
  console.log(`sync-proto: up to date (${PROTOS.length} protos)`)
  process.exit(0)
}

const lines = ['// Generated by scripts/sync-proto.mjs from the repository proto tree. Do not edit.']
for (const proto of PROTOS) {
  mkdirSync(dirname(proto.destination), { recursive: true })
  writeFileSync(proto.destination, proto.contents)
  lines.push(`// ${proto.posix}`)
  lines.push(`export const ${proto.exportName} = ${JSON.stringify(proto.contents.toString('utf8'))}`)
}
lines.push('')

mkdirSync(dirname(generated), { recursive: true })
writeFileSync(generated, lines.join('\n'))

for (const proto of PROTOS) {
  console.log(`sync-proto: ${proto.relative} <- ${proto.source}`)
}
