name: Cluster Binary

on:
  push:
    branches: [main]
    paths:
      - "rust/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "proto/**"
      - ".github/workflows/cluster-binary.yml"
      - ".github/workflows/cluster-binary-build.yml"
  pull_request:
    paths:
      - "rust/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "proto/**"
      - ".github/workflows/cluster-binary.yml"
      - ".github/workflows/cluster-binary-build.yml"

jobs:
  build:
    uses: ./.github/workflows/cluster-binary-build.yml
    with:
      upload_retention_days: 14
